import { lazy, Suspense } from 'react';
import { Routes, Route } from 'react-router-dom';
import { ProtectedRoute } from './ProtectedRoute';
import { CitizenLayout, AgentLayout, AdminLayout } from '../components/layouts';
import { useRealtime } from '../hooks/useRealtime';
const LandingPage=lazy(()=>import('../pages/public/LandingPage'));
const PublicMapPage=lazy(()=>import('../pages/public/PublicMapPage'));
const LoginPage=lazy(()=>import('../pages/public/AuthPages').then(m=>({default:m.LoginPage})));
const RegisterPage=lazy(()=>import('../pages/public/AuthPages').then(m=>({default:m.RegisterPage})));
const ForgotPasswordPage=lazy(()=>import('../pages/public/AuthPages').then(m=>({default:m.ForgotPasswordPage})));
const ResetPasswordPage=lazy(()=>import('../pages/public/AuthPages').then(m=>({default:m.ResetPasswordPage})));
const VerifyEmailPage=lazy(()=>import('../pages/public/AuthPages').then(m=>({default:m.VerifyEmailPage})));
const CitizenDashboard=lazy(()=>import('../pages/citizen/CitizenPages').then(m=>({default:m.CitizenDashboard})));
const NewReportPage=lazy(()=>import('../pages/citizen/CitizenPages').then(m=>({default:m.NewReportPage})));
const MyReportsPage=lazy(()=>import('../pages/citizen/CitizenPages').then(m=>({default:m.MyReportsPage})));
const ReportDetailPage=lazy(()=>import('../pages/citizen/CitizenPages').then(m=>({default:m.ReportDetailPage})));
const CitizenAnnouncements=lazy(()=>import('../pages/citizen/CitizenPages').then(m=>({default:m.CitizenAnnouncements})));
const ProfilePage=lazy(()=>import('../pages/citizen/CitizenPages').then(m=>({default:m.ProfilePage})));
const AgentDashboard=lazy(()=>import('../pages/agent/AgentPages').then(m=>({default:m.AgentDashboard})));
const PendingReportsPage=lazy(()=>import('../pages/agent/AgentPages').then(m=>({default:m.PendingReportsPage})));
const ReviewReportPage=lazy(()=>import('../pages/agent/AgentPages').then(m=>({default:m.ReviewReportPage})));
const AgentStatistics=lazy(()=>import('../pages/agent/AgentPages').then(m=>({default:m.AgentStatistics})));
const AgentAnnouncements=lazy(()=>import('../pages/agent/AgentPages').then(m=>({default:m.AgentAnnouncements})));
const AdminDashboard=lazy(()=>import('../pages/admin/AdminPages').then(m=>({default:m.AdminDashboard})));
const AgentsPage=lazy(()=>import('../pages/admin/AdminPages').then(m=>({default:m.AgentsPage})));
const ExportsPage=lazy(()=>import('../pages/admin/AdminPages').then(m=>({default:m.ExportsPage})));
const LogsPage=lazy(()=>import('../pages/admin/AdminPages').then(m=>({default:m.LogsPage})));
const ParametersPage=lazy(()=>import('../pages/admin/AdminPages').then(m=>({default:m.ParametersPage})));
const UsersPage=lazy(()=>import('../pages/admin/AdminPages').then(m=>({default:m.UsersPage})));
const AdminReportsPage=lazy(()=>import('../pages/admin/AdminPages').then(m=>({default:m.ReportsPage})));
export default function App(){useRealtime();return <Suspense fallback={<div className="page-loader">Cargando AlertApp...</div>}><Routes><Route path="/" element={<LandingPage/>}/><Route path="/mapa" element={<PublicMapPage/>}/><Route path="/login" element={<LoginPage/>}/><Route path="/registro" element={<RegisterPage/>}/><Route path="/recuperar-password" element={<ForgotPasswordPage/>}/><Route path="/restablecer-password" element={<ResetPasswordPage/>}/><Route path="/verificar-email" element={<VerifyEmailPage/>}/><Route element={<ProtectedRoute roles={['CIUDADANO']}/>}><Route element={<CitizenLayout/>}><Route path="/ciudadano" element={<CitizenDashboard/>}/><Route path="/ciudadano/reportar" element={<NewReportPage/>}/><Route path="/ciudadano/reportes" element={<MyReportsPage/>}/><Route path="/ciudadano/reportes/:id" element={<ReportDetailPage/>}/><Route path="/ciudadano/comunicados" element={<CitizenAnnouncements/>}/><Route path="/ciudadano/perfil" element={<ProfilePage/>}/></Route></Route><Route element={<ProtectedRoute roles={['AGENTE']}/>}><Route element={<AgentLayout/>}><Route path="/agente" element={<AgentDashboard/>}/><Route path="/agente/reportes" element={<PendingReportsPage/>}/><Route path="/agente/reportes/:id" element={<ReviewReportPage/>}/><Route path="/agente/estadisticas" element={<AgentStatistics/>}/><Route path="/agente/comunicados" element={<AgentAnnouncements/>}/></Route></Route><Route element={<ProtectedRoute roles={['ADMIN']}/>}><Route element={<AdminLayout/>}><Route path="/admin" element={<AdminDashboard/>}/><Route path="/admin/usuarios" element={<UsersPage/>}/><Route path="/admin/agentes" element={<AgentsPage/>}/><Route path="/admin/reportes" element={<AdminReportsPage/>}/><Route path="/admin/parametros" element={<ParametersPage/>}/><Route path="/admin/logs" element={<LogsPage/>}/><Route path="/admin/exportaciones" element={<ExportsPage/>}/></Route></Route><Route path="*" element={<div className="page-loader">Página no encontrada.</div>}/></Routes></Suspense>}
