import type { ReactNode } from 'react';
import { Bell, ChartColumn, ClipboardList, FileDown, Home, LogOut, MapPinned, Megaphone, Settings, ShieldCheck, User, Users } from 'lucide-react';
import { NavLink, Outlet, Link } from 'react-router-dom';
import { useAuth } from '../app/AuthProvider';
import { Logo } from './ui';
type Item={to:string;label:string;icon:typeof Home};
const citizen:Item[]=[{to:'/ciudadano',label:'Inicio',icon:Home},{to:'/mapa',label:'Mapa',icon:MapPinned},{to:'/ciudadano/reportar',label:'Reportar',icon:ShieldCheck},{to:'/ciudadano/reportes',label:'Mis reportes',icon:ClipboardList},{to:'/ciudadano/comunicados',label:'Comunicados',icon:Bell},{to:'/ciudadano/perfil',label:'Perfil',icon:User}];
const agent:Item[]=[{to:'/agente',label:'Dashboard',icon:Home},{to:'/agente/reportes',label:'Pendientes',icon:MapPinned},{to:'/agente/estadisticas',label:'Estadísticas',icon:ChartColumn},{to:'/agente/comunicados',label:'Comunicados',icon:Megaphone}];
const admin:Item[]=[{to:'/admin',label:'Dashboard',icon:Home},{to:'/admin/usuarios',label:'Ciudadanos',icon:Users},{to:'/admin/agentes',label:'Agentes',icon:ShieldCheck},{to:'/admin/reportes',label:'Reportes',icon:MapPinned},{to:'/admin/parametros',label:'Parámetros',icon:Settings},{to:'/admin/logs',label:'Logs',icon:ClipboardList},{to:'/admin/exportaciones',label:'Exportaciones',icon:FileDown}];
function Layout({items,theme,title}:{items:Item[];theme:'citizen'|'agent'|'admin';title:string}){ const {user,logout}=useAuth(); const dark=theme!=='citizen'; return <div className={`app-shell ${theme==='agent'?'shell-dark':theme==='admin'?'shell-admin':''}`}><aside className={`sidebar ${dark?'sidebar-dark':''} ${theme==='admin'?'sidebar-admin':''}`}><Logo light={dark}/><p className={`mt-2 mb-8 text-xs ${dark?'dark-muted':'text-slate-500'}`}>{title}</p><nav className="flex-1">{items.map(({to,label,icon:Icon})=><NavLink key={to} to={to} end={to.split('/').length===2} className="side-link"><Icon size={18}/>{label}</NavLink>)}</nav><button className={`side-link w-full ${dark?'text-slate-300':''}`} onClick={()=>void logout()}><LogOut size={18}/>Cerrar sesión</button></aside><div className="shell-content"><header className={`topbar ${dark?'topbar-dark':''}`}><div className="md:hidden"><Logo light={dark}/></div><span className={`hidden md:block text-sm ${dark?'text-slate-300':'text-slate-600'}`}>{title}</span><div className="flex items-center gap-3 text-sm"><span className={dark?'text-slate-200':'text-slate-700'}>{user?.nombres}</span><button aria-label="Cerrar sesión" className={dark?'text-slate-300':'text-slate-500'} onClick={()=>void logout()}><LogOut size={18}/></button></div></header><main className="main-area pb-20 md:pb-8"><Outlet/></main><nav className="mobile-nav">{items.slice(0,5).map(({to,label,icon:Icon})=><NavLink key={to} to={to} end={to.split('/').length===2} className="mobile-link"><Icon size={18}/>{label}</NavLink>)}</nav></div></div>; }
export const CitizenLayout=()=> <Layout items={citizen} theme="citizen" title="Panel ciudadano"/>;
export const AgentLayout=()=> <Layout items={agent} theme="agent" title="Centro operativo"/>;
export const AdminLayout=()=> <Layout items={admin} theme="admin" title="Administración"/>;
export function PublicHeader(){return <header className="public-header"><div className="container flex h-16 items-center justify-between"><Link to="/"><Logo/></Link><nav className="hidden items-center gap-7 text-sm text-slate-600 md:flex"><Link to="/mapa">Mapa público</Link><a href="/#funciones">Funciones</a><a href="/#prevencion">Prevención</a></nav><div className="flex gap-2"><Link className="btn-secondary hidden sm:inline-flex" to="/login">Ingresar</Link><Link className="btn-primary" to="/registro">Registrarme</Link></div></div></header>}
export function PublicLayout({children}:{children:ReactNode}){return <>{<PublicHeader/>}{children}<footer className="border-t border-slate-200 bg-white py-10"><div className="container flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><Logo/><p className="text-sm text-slate-500">AlertApp · Información ciudadana colaborativa. No reemplaza una denuncia oficial.</p></div></footer></>}
