import { Router } from 'express';
import { authenticate } from '../../middlewares/authenticate';
import { authorizeRoles } from '../../middlewares/authorizeRoles';
import { csrfProtection } from '../../middlewares/csrfProtection';
import { validateBody } from '../../middlewares/validateRequest';
import { asyncHandler } from '../../shared/utils/asyncHandler';
import * as controller from './admin.controller';
import { createAgentSchema, updateReportVisibilitySchema, updateUserSchema, updateUserStatusSchema } from './admin.schemas';
export const adminRouter=Router();
adminRouter.use(authenticate,authorizeRoles('ADMIN'));
adminRouter.get('/dashboard',asyncHandler(controller.dashboard));
adminRouter.get('/usuarios',asyncHandler(controller.listCitizens));
adminRouter.patch('/usuarios/:id',csrfProtection,validateBody(updateUserSchema),asyncHandler(controller.updateUser));
adminRouter.patch('/usuarios/:id/estado',csrfProtection,validateBody(updateUserStatusSchema),asyncHandler(controller.updateUserStatus));
adminRouter.get('/agentes',asyncHandler(controller.listAgents));
adminRouter.post('/agentes',csrfProtection,validateBody(createAgentSchema),asyncHandler(controller.createAgent));
adminRouter.get('/logs',asyncHandler(controller.listLogs));
adminRouter.get('/reportes',asyncHandler(controller.listReports));
adminRouter.get('/reportes/:id',asyncHandler(controller.adminReportDetail));
adminRouter.patch('/reportes/:id/visibilidad',csrfProtection,validateBody(updateReportVisibilitySchema),asyncHandler(controller.updateReportVisibility));
