import { zodResolver } from '@hookform/resolvers/zod';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Bell, ClipboardList, MapPinned, PlusCircle, ShieldAlert, Upload } from 'lucide-react';
import { useEffect, useMemo, useState, type ChangeEvent } from 'react';
import { useForm } from 'react-hook-form';
import { Link, useLocation, useNavigate, useParams } from 'react-router-dom';
import { z } from 'zod';
import { useAuth } from '../../app/AuthProvider';
import { LocationPicker } from '../../components/IncidentMap';
import { Disclaimer, EmptyState, ErrorPanel, StatusBadge } from '../../components/ui';
import { EvidenceImage } from '../../components/EvidenceImage';
import api, { apiMessage } from '../../services/api';
import type { Announcement, ApiResponse, IncidentType, ReportItem } from '../../types';
function date(value:string){return new Intl.DateTimeFormat('es-PE',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value));}
function EvidencePreview({ file }: { file: File }) {
  const [src, setSrc] = useState('');
  useEffect(() => { const url = URL.createObjectURL(file); setSrc(url); return () => URL.revokeObjectURL(url); }, [file]);
  return src ? <img className="h-20 w-20 rounded-lg object-cover" src={src} alt="Vista previa de evidencia"/> : null;
}

export function CitizenDashboard(){ const {user}=useAuth(); const reports=useQuery({queryKey:['my-reports'],queryFn:async()=>(await api.get<ApiResponse<ReportItem[]>>('/reportes/mios?limit=40')).data.data}); const announcements=useQuery({queryKey:['announcements'],queryFn:async()=>(await api.get<ApiResponse<Announcement[]>>('/comunicados')).data.data}); const counts=useMemo(()=>({total:reports.data?.length??0,pending:reports.data?.filter(r=>r.estado==='PENDIENTE').length??0,valid:reports.data?.filter(r=>r.estado==='VALIDADO').length??0}),[reports.data]); return <div className="space-y-6"><div><h1 className="page-title">Hola, {user?.nombres}</h1><p className="muted mt-2">Consulta el mapa y reporta situaciones de seguridad en tu comunidad.</p></div><Disclaimer/><div className="stats-grid"><Stat label="Mis reportes" value={counts.total}/><Stat label="Pendientes" value={counts.pending}/><Stat label="Validados" value={counts.valid}/><Stat label="Comunicados" value={announcements.data?.length??0}/></div><div className="grid gap-5 lg:grid-cols-3"><Link className="card flex items-center gap-4 hover:border-blue-300" to="/mapa"><MapPinned className="text-blue-600"/><div><h2 className="font-semibold">Explorar mapa</h2><p className="muted">Incidentes visibles en Ica</p></div></Link><Link className="card flex items-center gap-4 hover:border-blue-300" to="/ciudadano/reportar"><PlusCircle className="text-blue-600"/><div><h2 className="font-semibold">Nuevo reporte</h2><p className="muted">Publicar un incidente</p></div></Link><Link className="card flex items-center gap-4 hover:border-blue-300" to="/ciudadano/reportes"><ClipboardList className="text-blue-600"/><div><h2 className="font-semibold">Mi historial</h2><p className="muted">Revisar estados</p></div></Link></div><section className="card"><h2 className="mb-4 font-semibold">Últimos comunicados</h2>{announcements.data?.length?announcements.data.slice(0,3).map(a=><article className="border-b border-slate-100 py-3 last:border-0" key={a.id}><span className="badge bg-blue-50 text-blue-700">{a.nivel}</span><h3 className="mt-2 font-medium">{a.titulo}</h3><p className="muted mt-1">{a.contenido}</p></article>):<EmptyState title="Sin comunicados" text="No hay comunicados preventivos publicados."/>}</section></div> }
function Stat({label,value}:{label:string;value:number}){return <div className="stat"><p className="muted">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></div>}
const reportSchema=z.object({tipoIncidenteId:z.string().uuid('Selecciona un tipo.'),titulo:z.string().min(5).max(150),descripcion:z.string().min(15).max(1500),ubicacionReferencia:z.string().max(255),distrito:z.string().min(2).max(100),fechaHoraIncidente:z.string().min(1),prioridadReportada:z.enum(['BAJA','MEDIA','ALTA'])});
export function NewReportPage(){const navigate=useNavigate(); const [location,setLocation]=useState<[number,number]>([-14.0678,-75.7286]); const [files,setFiles]=useState<File[]>([]); const [error,setError]=useState(''); const types=useQuery({queryKey:['types'],queryFn:async()=>(await api.get<ApiResponse<IncidentType[]>>('/catalogos/tipos-incidente')).data.data}); const {register,handleSubmit,formState:{errors,isSubmitting}}=useForm<z.infer<typeof reportSchema>>({resolver:zodResolver(reportSchema),defaultValues:{distrito:'Ica',prioridadReportada:'MEDIA',fechaHoraIncidente:new Date().toISOString().slice(0,16)}}); const submit=handleSubmit(async(v)=>{try{const form=new FormData();Object.entries(v).forEach(([k,val])=>form.append(k,String(val)));form.append('latitud',String(location[0]));form.append('longitud',String(location[1]));files.forEach(file=>form.append('evidencias',file));const {data}=await api.post('/reportes',form);navigate(`/ciudadano/reportes/${data.data.id}`, { state: { success: 'Reporte publicado. Será visible como no verificado hasta la revisión operativa.' } });}catch(e){setError(apiMessage(e));}}); function selectFiles(event:ChangeEvent<HTMLInputElement>){ const selected=Array.from(event.target.files??[]); const allowed=selected.filter(f=>['image/jpeg','image/png','image/webp'].includes(f.type)&&f.size<=5*1024*1024).slice(0,3); setFiles(allowed); if(allowed.length!==selected.length)setError('Solo se aceptan hasta 3 imágenes JPG, PNG o WebP de máximo 5 MB.'); }
return <div className="space-y-5"><div><h1 className="page-title">Registrar incidente</h1><p className="muted mt-2">Tu ubicación aparecerá públicamente como reporte no verificado; el detalle textual y la evidencia se mantienen protegidos hasta revisión.</p></div><Disclaimer/><form onSubmit={submit} className="grid gap-5 xl:grid-cols-[1fr_420px]"><section className="card space-y-4">{error&&<ErrorPanel message={error}/>}<div className="form-grid two"><label><span className="label">Tipo de incidente</span><select className="input" {...register('tipoIncidenteId')}><option value="">Selecciona</option>{types.data?.map(type=><option value={type.id} key={type.id}>{type.nombre}</option>)}</select><small className="text-red-600">{errors.tipoIncidenteId?.message}</small></label><label><span className="label">Prioridad reportada</span><select className="input" {...register('prioridadReportada')}><option>BAJA</option><option>MEDIA</option><option>ALTA</option></select></label></div><label><span className="label">Título</span><input className="input" {...register('titulo')} placeholder="Describe brevemente el incidente"/><small className="text-red-600">{errors.titulo?.message}</small></label><label><span className="label">Descripción</span><textarea className="input min-h-32" {...register('descripcion')} placeholder="Evita incluir datos personales innecesarios."/><small className="text-red-600">{errors.descripcion?.message}</small></label><div className="form-grid two"><label><span className="label">Fecha y hora</span><input className="input" type="datetime-local" {...register('fechaHoraIncidente')}/></label><label><span className="label">Distrito</span><input className="input" {...register('distrito')}/></label></div><label><span className="label">Referencia de ubicación</span><input className="input" {...register('ubicacionReferencia')} placeholder="Ej. Cerca de una avenida o parque"/></label><label className="block"><span className="label">Evidencias fotográficas opcionales</span><div className="rounded-xl border border-dashed border-blue-200 bg-blue-50 p-4"><input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={selectFiles}/><p className="mt-2 text-xs text-slate-600">Máximo 3 imágenes de 5 MB. Evita rostros, documentos y datos personales.</p></div></label><div className="flex gap-3">{files.map(file=><EvidencePreview key={`${file.name}-${file.size}`} file={file}/>)}</div><button disabled={isSubmitting} className="btn-primary w-full"><Upload size={18}/>{isSubmitting?'Publicando...':'Publicar reporte pendiente'}</button></section><section className="card"><h2 className="mb-3 font-semibold">Selecciona la ubicación exacta</h2><LocationPicker value={location} onChange={setLocation}/><p className="mt-4 text-sm font-medium text-slate-700">Coordenadas: {location[0].toFixed(6)}, {location[1].toFixed(6)}</p></section></form></div>}
export function MyReportsPage(){ const [state,setState]=useState(''); const {data,isLoading,error}=useQuery({queryKey:['my-reports',state],queryFn:async()=>(await api.get<ApiResponse<ReportItem[]>>(`/reportes/mios?estado=${state}`)).data.data}); return <div className="space-y-5"><div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><h1 className="page-title">Mis reportes</h1><p className="muted mt-2">Historial y estado de tus publicaciones.</p></div><select className="input max-w-52" value={state} onChange={e=>setState(e.target.value)}><option value="">Todos los estados</option><option value="PENDIENTE">Pendientes</option><option value="VALIDADO">Validados</option><option value="RECHAZADO">Rechazados</option></select></div>{error?<ErrorPanel message={apiMessage(error)}/>:isLoading?<p>Cargando...</p>:data?.length?<div className="grid gap-3">{data.map(report=><Link to={`/ciudadano/reportes/${report.id}`} className="card flex flex-col justify-between gap-3 hover:border-blue-300 md:flex-row md:items-center" key={report.id}><div><div className="flex gap-2"><StatusBadge status={report.estado}/>{report.esDatoDemostrativo&&<span className="badge-demo">Demostrativo</span>}</div><h2 className="mt-2 font-semibold">{report.tipoNombre}: {report.titulo}</h2><p className="muted mt-1">{date(report.createdAt)} · {report.ubicacionReferencia||report.distrito}</p></div><span className="text-sm font-medium text-blue-600">Ver detalle →</span></Link>)}</div>:<EmptyState title="No has creado reportes" text="Publica un incidente desde el formulario para comenzar."/>}</div>}
export function ReportDetailPage(){const {id}=useParams();const location=useLocation();const client=useQueryClient();const [notice,setNotice]=useState((location.state as {success?:string}|null)?.success ?? '');const query=useQuery({queryKey:['my-report',id],queryFn:async()=>(await api.get<ApiResponse<ReportItem>>(`/reportes/mios/${id}`)).data.data});const withdraw=useMutation({mutationFn:async()=>api.patch(`/reportes/${id}/retirar`),onSuccess:()=>{setNotice('Reporte retirado correctamente.');void client.invalidateQueries({queryKey:['my-report',id]});}});if(query.isLoading)return <p>Cargando...</p>;if(query.error||!query.data)return <ErrorPanel message={apiMessage(query.error)}/>;const r=query.data;return <div className="space-y-5"><Link className="text-sm font-medium text-blue-600" to="/ciudadano/reportes">← Volver</Link>{notice&&<div className="rounded-xl border border-green-200 bg-green-50 p-4 text-sm text-green-800">{notice}</div>}<div className="card space-y-5"><div className="flex flex-wrap items-center gap-2"><StatusBadge status={r.estado}/>{r.esDatoDemostrativo&&<span className="badge-demo">Dato demostrativo</span>}</div><h1 className="page-title">{r.tipoNombre}: {r.titulo}</h1><p className="text-slate-700">{r.descripcion}</p><div className="grid gap-3 text-sm md:grid-cols-3"><p><strong>Fecha:</strong><br/>{date(r.fechaHoraIncidente)}</p><p><strong>Ubicación:</strong><br/>{r.ubicacionReferencia||r.distrito}</p><p><strong>Prioridad:</strong><br/>{r.prioridadReportada}</p></div>{r.evidencias?.length?<div><h2 className="mb-3 font-semibold">Evidencias</h2><div className="flex gap-3">{r.evidencias.map(e=><EvidenceImage className="h-40 w-40 rounded-xl object-cover" id={e.id} alt="Evidencia adjunta" key={e.id}/>)}</div></div>:null}{r.validacion&&<div className="rounded-xl bg-slate-50 p-4"><h2 className="font-semibold">Revisión del agente</h2><p className="mt-2 text-sm">{r.validacion.observaciones||'Sin observaciones adicionales.'}</p></div>}{r.estado==='PENDIENTE'&&<button onClick={()=>{if(window.confirm('¿Confirmas que deseas retirar este reporte pendiente? Dejará de verse en el mapa público.')) withdraw.mutate();}} disabled={withdraw.isPending} className="btn-secondary">{withdraw.isPending?'Retirando...':'Retirar reporte'}</button>}{withdraw.error&&<ErrorPanel message={apiMessage(withdraw.error)}/>}</div></div>}
export function CitizenAnnouncements(){const {data}=useQuery({queryKey:['announcements'],queryFn:async()=>(await api.get<ApiResponse<Announcement[]>>('/comunicados')).data.data});return <div className="space-y-5"><h1 className="page-title">Comunicados preventivos</h1>{data?.length?data.map(a=><article className="card" key={a.id}><span className={`badge ${a.nivel==='URGENTE'?'bg-red-100 text-red-800':'bg-blue-100 text-blue-800'}`}>{a.nivel}</span><h2 className="mt-3 text-lg font-semibold">{a.titulo}</h2><p className="mt-2 text-slate-600">{a.contenido}</p><p className="muted mt-4">{a.publishedAt?date(a.publishedAt):''} {a.esDatoDemostrativo?' · Contenido demostrativo':''}</p></article>):<EmptyState title="Sin comunicados" text="No existen comunicados activos."/>}</div>}
export function ProfilePage(){const {user}=useAuth();return <div className="max-w-2xl space-y-5"><h1 className="page-title">Mi perfil</h1><div className="card grid gap-4 md:grid-cols-2"><p><span className="muted">Nombre</span><br/><strong>{user?.nombres} {user?.apellidos}</strong></p><p><span className="muted">Correo</span><br/><strong>{user?.email}</strong></p><p><span className="muted">Rol</span><br/><strong>Ciudadano</strong></p><p><span className="muted">Correo verificado</span><br/><strong>{user?.emailVerifiedAt?'Sí':'No'}</strong></p></div></div>}
