import type { Request, Response } from 'express';
import { and, desc, eq, gt, isNull, or } from 'drizzle-orm';
import { db } from '../../config/database';
import { announcements, users } from '../../db/schema';
import { ApiError } from '../../shared/errors/ApiError';
import { emitPublicEvent } from '../../realtime/socket';
import { writeAuditLog } from '../audit/audit.service';
import { announcementBodySchema, announcementUpdateSchema } from './announcements.schemas';
function idFrom(request:Request){const id=Array.isArray(request.params.id)?request.params.id[0]:request.params.id;if(!id)throw new ApiError(400,'Identificador inválido.','INVALID_ID');return id;}
export async function listPublic(_request:Request,response:Response):Promise<void>{
  const data=await db.select({id:announcements.id,titulo:announcements.titulo,contenido:announcements.contenido,nivel:announcements.nivel,zonaReferencia:announcements.zonaReferencia,publishedAt:announcements.publishedAt,expiresAt:announcements.expiresAt,esDatoDemostrativo:announcements.esDatoDemostrativo}).from(announcements).where(and(eq(announcements.estado,'PUBLICADO'),or(isNull(announcements.expiresAt),gt(announcements.expiresAt,new Date())))).orderBy(desc(announcements.publishedAt));
  response.json({ok:true,data});
}
export async function getPublic(request:Request,response:Response):Promise<void>{ const id=idFrom(request); const rows=await db.select().from(announcements).where(and(eq(announcements.id,id),eq(announcements.estado,'PUBLICADO'))).limit(1); if(!rows[0])throw new ApiError(404,'Comunicado no disponible.','ANNOUNCEMENT_NOT_FOUND'); response.json({ok:true,data:rows[0]}); }
export async function listManaged(_request:Request,response:Response):Promise<void>{ const data=await db.select({id:announcements.id,titulo:announcements.titulo,contenido:announcements.contenido,nivel:announcements.nivel,zonaReferencia:announcements.zonaReferencia,estado:announcements.estado,publishedAt:announcements.publishedAt,expiresAt:announcements.expiresAt,createdAt:announcements.createdAt,authorName:users.nombres}).from(announcements).innerJoin(users,eq(announcements.authorId,users.id)).orderBy(desc(announcements.createdAt)); response.json({ok:true,data}); }
export async function create(request:Request,response:Response):Promise<void>{ if(!request.user)throw new ApiError(401,'Debes iniciar sesión.','AUTH_REQUIRED'); const parsed=announcementBodySchema.safeParse(request.body); if(!parsed.success)throw new ApiError(422,'Datos del comunicado inválidos.','VALIDATION_ERROR',parsed.error.flatten()); const values={authorId:request.user.id,titulo:parsed.data.titulo,contenido:parsed.data.contenido,nivel:parsed.data.nivel,zonaReferencia:parsed.data.zonaReferencia||null,expiresAt:parsed.data.expiresAt?new Date(parsed.data.expiresAt):null}; const created=await db.insert(announcements).values(values).returning(); await writeAuditLog({actorUserId:request.user.id,accion:'COMUNICADO_CREADO',entidad:'COMUNICADO',entidadId:created[0].id,resultado:'EXITO',ip:request.ip}); response.status(201).json({ok:true,data:created[0],message:'Comunicado guardado como borrador.'}); }
export async function update(request:Request,response:Response):Promise<void>{ if(!request.user)throw new ApiError(401,'Debes iniciar sesión.','AUTH_REQUIRED'); const id=idFrom(request); const parsed=announcementUpdateSchema.safeParse(request.body); if(!parsed.success)throw new ApiError(422,'Datos inválidos.','VALIDATION_ERROR',parsed.error.flatten()); const update={...parsed.data,zonaReferencia:parsed.data.zonaReferencia||null,expiresAt:parsed.data.expiresAt===undefined?undefined:parsed.data.expiresAt?new Date(parsed.data.expiresAt):null,updatedAt:new Date()}; const rows=await db.update(announcements).set(update).where(eq(announcements.id,id)).returning(); if(!rows[0])throw new ApiError(404,'Comunicado no encontrado.','ANNOUNCEMENT_NOT_FOUND'); await writeAuditLog({actorUserId:request.user.id,accion:'COMUNICADO_EDITADO',entidad:'COMUNICADO',entidadId:id,resultado:'EXITO',ip:request.ip}); response.json({ok:true,data:rows[0],message:'Comunicado actualizado.'}); }
export async function publish(request:Request,response:Response):Promise<void>{ if(!request.user)throw new ApiError(401,'Debes iniciar sesión.','AUTH_REQUIRED'); const id=idFrom(request); const rows=await db.update(announcements).set({estado:'PUBLICADO',publishedAt:new Date(),updatedAt:new Date()}).where(eq(announcements.id,id)).returning(); if(!rows[0])throw new ApiError(404,'Comunicado no encontrado.','ANNOUNCEMENT_NOT_FOUND'); await writeAuditLog({actorUserId:request.user.id,accion:'COMUNICADO_PUBLICADO',entidad:'COMUNICADO',entidadId:id,resultado:'EXITO',ip:request.ip}); emitPublicEvent('comunicado:publicado',{id}); response.json({ok:true,data:rows[0],message:'Comunicado publicado.'}); }
export async function archive(request:Request,response:Response):Promise<void>{ if(!request.user)throw new ApiError(401,'Debes iniciar sesión.','AUTH_REQUIRED'); const id=idFrom(request); const rows=await db.update(announcements).set({estado:'ARCHIVADO',updatedAt:new Date()}).where(eq(announcements.id,id)).returning(); if(!rows[0])throw new ApiError(404,'Comunicado no encontrado.','ANNOUNCEMENT_NOT_FOUND'); await writeAuditLog({actorUserId:request.user.id,accion:'COMUNICADO_ARCHIVADO',entidad:'COMUNICADO',entidadId:id,resultado:'EXITO',ip:request.ip}); emitPublicEvent('comunicado:actualizado',{id}); response.json({ok:true,message:'Comunicado archivado.'}); }
