import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Eye, EyeOff, FileDown, Pencil, X } from 'lucide-react';
import { useEffect, useState, type FormEvent } from 'react';
import api, { apiMessage, downloadPost } from '../../services/api';
import type { ApiResponse, IncidentType, ReportItem } from '../../types';
import { EvidenceImage } from '../../components/EvidenceImage';
import { EmptyState, ErrorPanel, StatusBadge } from '../../components/ui';

type UserRow={id:string;nombres:string;apellidos:string;email:string;estado:string;rol:string;createdAt:string};
function date(value:string){return new Intl.DateTimeFormat('es-PE',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value));}
function Stat({label,value}:{label:string;value:number}){return <div className="dark-card"><p className="dark-muted text-sm">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></div>;}
export function AdminDashboard(){const {data}=useQuery({queryKey:['admin-dashboard'],queryFn:async()=>(await api.get('/admin/dashboard')).data.data});return <div className="space-y-6"><div><h1 className="page-title">Panel administrativo</h1><p className="dark-muted mt-2">Supervisión y auditoría general de AlertApp.</p></div><div className="stats-grid"><Stat label="Ciudadanos" value={data?.ciudadanos??0}/><Stat label="Agentes" value={data?.agentes??0}/><Stat label="Reportes" value={data?.reportes??0}/><Stat label="Pendientes" value={data?.pendientes??0}/><Stat label="Validados" value={data?.validados??0}/><Stat label="Comunicados" value={data?.comunicados??0}/></div><section className="dark-card"><h2 className="mb-4 text-lg font-semibold">Actividad reciente</h2>{data?.actividadReciente?.length?<div className="space-y-2">{data.actividadReciente.map((log:{id:string;accion:string;entidad:string;createdAt:string})=><div className="flex items-center justify-between rounded-lg bg-slate-900 p-3" key={log.id}><span className="text-sm">{log.accion} · {log.entidad}</span><span className="text-xs text-slate-400">{date(log.createdAt)}</span></div>)}</div>:<EmptyState title="Sin actividad" text="Todavía no existen registros."/>}</section></div>;}
function UsersTable({role}:{role:'CIUDADANO'|'AGENTE'}){
 const client=useQueryClient(); const [search,setSearch]=useState(''); const [estado,setEstado]=useState(''); const [editing,setEditing]=useState<UserRow|null>(null);
 const users=useQuery({queryKey:['admin-users',role,search,estado],queryFn:async()=>(await api.get<ApiResponse<UserRow[]>>(`/admin/${role==='AGENTE'?'agentes':'usuarios'}?search=${encodeURIComponent(search)}&estado=${estado}&limit=50`)).data.data});
 const change=useMutation({mutationFn:async({id,next}:{id:string;next:string})=>api.patch(`/admin/usuarios/${id}/estado`,{estado:next,motivo:'Actualización solicitada desde el panel administrativo.'}),onSuccess:()=>void client.invalidateQueries({queryKey:['admin-users']})});
 const edit=useMutation({mutationFn:async()=>api.patch(`/admin/usuarios/${editing?.id}`,{nombres:editing?.nombres,apellidos:editing?.apellidos,email:editing?.email}),onSuccess:()=>{setEditing(null);void client.invalidateQueries({queryKey:['admin-users']});}});
 return <><div className="mb-4 flex flex-col gap-3 sm:flex-row"><input className="input dark-input" placeholder="Buscar nombre o correo" value={search} onChange={e=>setSearch(e.target.value)}/><select className="input dark-input sm:max-w-48" value={estado} onChange={e=>setEstado(e.target.value)}><option value="">Todos</option><option>ACTIVO</option><option>INACTIVO</option><option>BLOQUEADO</option></select></div>{users.error?<ErrorPanel message={apiMessage(users.error)}/>:<div className="table-wrap dark-table"><table><thead><tr><th>Nombre</th><th>Correo</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{users.data?.map(user=><tr key={user.id}><td>{user.nombres} {user.apellidos}</td><td>{user.email}</td><td>{user.estado}</td><td><div className="flex flex-wrap gap-2"><button className="btn-secondary" onClick={()=>setEditing(user)}><Pencil size={15}/>Editar</button><button className={user.estado==='ACTIVO'?'btn-danger':'btn-success'} onClick={()=>{const next=user.estado==='ACTIVO'?'INACTIVO':'ACTIVO';if(window.confirm(`¿Confirmas ${next==='ACTIVO'?'activar':'desactivar'} esta cuenta? La acción quedará auditada.`)) change.mutate({id:user.id,next});}}>{user.estado==='ACTIVO'?'Desactivar':'Activar'}</button></div></td></tr>)}</tbody></table></div>}{change.error&&<ErrorPanel message={apiMessage(change.error)}/>} {editing&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/60 p-4"><form className="dark-card w-full max-w-lg space-y-4" onSubmit={(e:FormEvent)=>{e.preventDefault();edit.mutate();}}><div className="flex items-center justify-between"><h2 className="text-xl font-semibold">Editar {role==='AGENTE'?'agente':'ciudadano'}</h2><button type="button" onClick={()=>setEditing(null)}><X/></button></div><input required className="input dark-input" value={editing.nombres} onChange={e=>setEditing({...editing,nombres:e.target.value})}/><input required className="input dark-input" value={editing.apellidos} onChange={e=>setEditing({...editing,apellidos:e.target.value})}/><input required type="email" className="input dark-input" value={editing.email} onChange={e=>setEditing({...editing,email:e.target.value})}/><button disabled={edit.isPending} className="btn-danger w-full">Guardar cambios</button>{edit.error&&<ErrorPanel message={apiMessage(edit.error)}/>}</form></div>}</>;
}
export function UsersPage(){return <div className="space-y-5"><h1 className="page-title">Gestión de ciudadanos</h1><section className="dark-card"><UsersTable role="CIUDADANO"/></section></div>;}
export function AgentsPage(){const client=useQueryClient();const [form,setForm]=useState({nombres:'',apellidos:'',email:'',password:''});const create=useMutation({mutationFn:async()=>api.post('/admin/agentes',form),onSuccess:()=>{setForm({nombres:'',apellidos:'',email:'',password:''});void client.invalidateQueries({queryKey:['admin-users']});}});return <div className="grid gap-5 xl:grid-cols-[370px_1fr]"><form className="dark-card space-y-4" onSubmit={(e:FormEvent)=>{e.preventDefault();create.mutate();}}><h1 className="text-xl font-semibold">Crear agente</h1><input required className="input dark-input" placeholder="Nombres" value={form.nombres} onChange={e=>setForm({...form,nombres:e.target.value})}/><input required className="input dark-input" placeholder="Apellidos" value={form.apellidos} onChange={e=>setForm({...form,apellidos:e.target.value})}/><input required type="email" className="input dark-input" placeholder="Correo" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input required type="password" className="input dark-input" placeholder="Contraseña temporal segura" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><p className="text-xs text-slate-400">Entrega la contraseña temporal por un canal seguro. Esta versión registra la creación, pero el cambio forzado al primer ingreso queda como endurecimiento posterior.</p><button className="btn-danger w-full">Crear agente</button>{create.error&&<ErrorPanel message={apiMessage(create.error)}/>}</form><section className="dark-card"><h2 className="mb-4 text-xl font-semibold">Agentes operativos</h2><UsersTable role="AGENTE"/></section></div>;}
export function ReportsPage(){
 const client=useQueryClient(); const [estado,setEstado]=useState(''); const [selected,setSelected]=useState<ReportItem|null>(null);
 const query=useQuery({queryKey:['admin-reports',estado],queryFn:async()=>(await api.get<ApiResponse<ReportItem[]>>(`/admin/reportes?estado=${estado}&limit=80`)).data.data});
 const detail=useQuery({queryKey:['admin-report-detail',selected?.id],queryFn:async()=>(await api.get<ApiResponse<ReportItem>>(`/admin/reportes/${selected?.id}`)).data.data,enabled:!!selected?.id});
 const visibility=useMutation({mutationFn:async(report:ReportItem)=>api.patch(`/admin/reportes/${report.id}/visibilidad`,{visiblePublicamente:!report.visiblePublicamente,motivo:'Moderación administrativa por protección de información pública.'}),onSuccess:()=>{void client.invalidateQueries({queryKey:['admin-reports']});void client.invalidateQueries({queryKey:['admin-report-detail']});}});
 return <div className="space-y-5"><div className="flex flex-col justify-between gap-3 md:flex-row md:items-end"><div><h1 className="page-title">Supervisión de reportes</h1><p className="dark-muted mt-2">Acceso administrativo auditado a reportes y evidencias.</p></div><select className="input dark-input max-w-56" value={estado} onChange={e=>setEstado(e.target.value)}><option value="">Todos los estados</option><option>PENDIENTE</option><option>VALIDADO</option><option>RECHAZADO</option><option>RETIRADO</option></select></div><section className="dark-card"><div className="table-wrap dark-table"><table><thead><tr><th>Reporte</th><th>Ciudadano</th><th>Estado</th><th>Visibilidad</th><th></th></tr></thead><tbody>{query.data?.map(report=><tr key={report.id}><td>{report.tipoNombre}<br/><span className="text-xs text-slate-400">{report.titulo}</span></td><td>{report.ciudadanoNombre}</td><td><StatusBadge status={report.estado}/></td><td>{report.visiblePublicamente?'Público':'Oculto'}</td><td><button className="btn-secondary" onClick={()=>setSelected(report)}>Ver</button></td></tr>)}</tbody></table></div>{!query.data?.length&&<EmptyState title="Sin reportes" text="No hay registros para este filtro."/>}</section>{selected&&detail.data&&<div className="fixed inset-0 z-50 overflow-y-auto bg-black/60 p-4"><div className="dark-card mx-auto my-8 max-w-3xl space-y-4"><div className="flex items-start justify-between"><div><StatusBadge status={detail.data.estado}/><h2 className="mt-3 text-xl font-semibold">{detail.data.tipoNombre}: {detail.data.titulo}</h2></div><button onClick={()=>setSelected(null)}><X/></button></div><p className="text-slate-200">{detail.data.descripcion}</p><div className="grid gap-3 text-sm md:grid-cols-3"><p><span className="dark-muted">Ciudadano</span><br/>{detail.data.ciudadanoNombre}<br/>{detail.data.ciudadanoEmail}</p><p><span className="dark-muted">Fecha</span><br/>{date(detail.data.fechaHoraIncidente)}</p><p><span className="dark-muted">Coordenadas</span><br/>{detail.data.latitud}, {detail.data.longitud}</p></div>{detail.data.evidencias?.length?<div><h3 className="mb-2 font-semibold">Evidencias protegidas</h3><div className="flex gap-3">{detail.data.evidencias.map(item=><EvidenceImage key={item.id} id={item.id} alt="Evidencia del reporte" className="h-40 w-40 rounded-xl object-cover"/>)}</div></div>:null}<button className={detail.data.visiblePublicamente?'btn-danger':'btn-success'} onClick={()=>{if(window.confirm(`¿Confirmas ${detail.data.visiblePublicamente?'ocultar':'restaurar'} este reporte en el mapa público?`)) visibility.mutate(detail.data);}}>{detail.data.visiblePublicamente?<><EyeOff size={16}/>Ocultar del mapa público</>:<><Eye size={16}/>Restaurar visibilidad</>}</button>{visibility.error&&<ErrorPanel message={apiMessage(visibility.error)}/>}</div></div>}</div>;
}
export function ParametersPage(){
 const client=useQueryClient();
 const query=useQuery({queryKey:['parameters'],queryFn:async()=>(await api.get('/admin/parametros')).data.data as {parameters:{id:string;clave:string;descripcion:string;valor:{texto?:string;cantidad?:number;activo?:boolean};editable:boolean}[];incidentTypes:IncidentType[]}});
 const [legalText,setLegalText]=useState('');
 useEffect(()=>{const current=query.data?.parameters.find(parameter=>parameter.clave==='AVISO_LEGAL')?.valor.texto; if(current)setLegalText(current);},[query.data]);
 const saveLegal=useMutation({mutationFn:async()=>api.patch('/admin/parametros/AVISO_LEGAL',{valor:{texto:legalText}}),onSuccess:()=>void client.invalidateQueries({queryKey:['parameters']})});
 const toggle=useMutation({mutationFn:async(type:IncidentType)=>api.patch(`/admin/parametros/tipos-incidente/${type.id}/estado`,{activo:!type.activo}),onSuccess:()=>void client.invalidateQueries({queryKey:['parameters']})});
 return <div className="space-y-5"><h1 className="page-title">Parámetros del sistema</h1><section className="dark-card space-y-4"><h2 className="font-semibold">Aviso legal visible</h2><label><span className="dark-muted mb-2 block text-sm">Texto mostrado a ciudadanos</span><textarea className="input dark-input min-h-24" value={legalText} onChange={e=>setLegalText(e.target.value)} maxLength={500}/></label><button className="btn-danger" disabled={saveLegal.isPending||legalText.trim().length<20} onClick={()=>{if(window.confirm('¿Guardar el aviso legal? La acción quedará auditada.')) saveLegal.mutate();}}>{saveLegal.isPending?'Guardando...':'Guardar aviso'}</button>{saveLegal.error&&<ErrorPanel message={apiMessage(saveLegal.error)}/>}</section><section className="dark-card"><h2 className="mb-4 font-semibold">Configuraciones protegidas</h2><div className="space-y-3">{query.data?.parameters.filter(parameter=>parameter.clave!=='AVISO_LEGAL').map(parameter=><div className="rounded-xl bg-slate-900 p-4" key={parameter.id}><p className="font-medium">{parameter.clave}</p><p className="mt-1 text-sm text-slate-400">{parameter.descripcion}</p><pre className="mt-2 text-xs text-slate-300">{JSON.stringify(parameter.valor)}</pre><p className="mt-2 text-xs text-amber-300">Protegido: requiere configuración o revisión técnica.</p></div>)}</div></section><section className="dark-card"><h2 className="mb-4 font-semibold">Tipos de incidente habilitados</h2><div className="grid gap-3 md:grid-cols-2">{query.data?.incidentTypes.map(type=><div className="flex items-center justify-between gap-3 rounded-xl bg-slate-900 p-3" key={type.id}><span className="text-sm">{type.nombre}</span><button className={type.activo?'btn-danger':'btn-success'} onClick={()=>{if(window.confirm(`¿Confirmas ${type.activo?'desactivar':'activar'} la categoría ${type.nombre}?`)) toggle.mutate(type);}}>{type.activo?'Desactivar':'Activar'}</button></div>)}</div>{toggle.error&&<ErrorPanel message={apiMessage(toggle.error)}/>}</section></div>;
}
export function LogsPage(){
 const [filters,setFilters]=useState({accion:'',entidad:'',actor:'',desde:'',hasta:''});
 const params=new URLSearchParams(Object.entries(filters).filter(([,value])=>value));
 const logs=useQuery({queryKey:['logs',filters],queryFn:async()=>(await api.get(`/admin/logs?${params}&limit=80`)).data.data});
 return <div className="space-y-5"><h1 className="page-title">Auditoría de actividad</h1><section className="dark-card"><div className="mb-4 grid gap-3 md:grid-cols-3 lg:grid-cols-5"><input className="input dark-input" placeholder="Acción" value={filters.accion} onChange={e=>setFilters({...filters,accion:e.target.value})}/><input className="input dark-input" placeholder="Entidad" value={filters.entidad} onChange={e=>setFilters({...filters,entidad:e.target.value})}/><input className="input dark-input" placeholder="Usuario o correo" value={filters.actor} onChange={e=>setFilters({...filters,actor:e.target.value})}/><input className="input dark-input" type="date" value={filters.desde} onChange={e=>setFilters({...filters,desde:e.target.value})}/><input className="input dark-input" type="date" value={filters.hasta} onChange={e=>setFilters({...filters,hasta:e.target.value})}/></div><div className="table-wrap dark-table"><table><thead><tr><th>Fecha</th><th>Usuario</th><th>Acción</th><th>Entidad</th><th>Resultado</th></tr></thead><tbody>{logs.data?.map((log:{id:string;createdAt:string;actorNombre?:string;actorEmail?:string;accion:string;entidad:string;resultado:string})=><tr key={log.id}><td>{date(log.createdAt)}</td><td>{log.actorNombre||'Sistema'}<br/><span className="text-xs text-slate-400">{log.actorEmail}</span></td><td>{log.accion}</td><td>{log.entidad}</td><td>{log.resultado}</td></tr>)}</tbody></table></div></section></div>;
}
export function ExportsPage(){const query=useQuery({queryKey:['exports'],queryFn:async()=>(await api.get('/admin/exportaciones')).data.data});const backup=useQuery({queryKey:['backup-status'],queryFn:async()=>(await api.get('/admin/exportaciones/backup-estado')).data.data});return <div className="space-y-5"><h1 className="page-title">Exportaciones y respaldos</h1><section className="dark-card"><h2 className="font-semibold">Exportar información permitida</h2><p className="dark-muted mt-2 text-sm">Las exportaciones no contienen contraseñas ni tokens.</p><div className="mt-5 flex flex-wrap gap-3"><button className="btn-danger" onClick={()=>{if(window.confirm('¿Generar la exportación de reportes? Esta acción quedará auditada.')) void downloadPost('/admin/exportaciones/reportes','alertapp-reportes.csv');}}><FileDown size={17}/>Exportar reportes</button><button className="btn-secondary" onClick={()=>{if(window.confirm('¿Generar la exportación de logs? Esta acción quedará auditada.')) void downloadPost('/admin/exportaciones/logs','alertapp-auditoria.csv');}}><FileDown size={17}/>Exportar logs</button></div></section><section className="dark-card"><h2 className="font-semibold">Respaldo de base de datos</h2><p className="dark-muted mt-3 text-sm">{backup.data?.message}</p></section><section className="dark-card"><h2 className="mb-4 font-semibold">Historial</h2>{query.data?.length?<div className="space-y-2">{query.data.map((record:{id:string;tipo:string;estado:string;createdAt:string})=><div key={record.id} className="flex justify-between rounded-xl bg-slate-900 p-3 text-sm"><span>{record.tipo}</span><span>{record.estado} · {date(record.createdAt)}</span></div>)}</div>:<EmptyState title="Sin exportaciones" text="Aún no se generaron archivos."/>}</section></div>;}
