import { zodResolver } from '@hookform/resolvers/zod';
import { Eye, EyeOff, ShieldCheck } from 'lucide-react';
import { useEffect, useState, type ReactNode } from 'react';
import { useForm } from 'react-hook-form';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { z } from 'zod';
import { useAuth } from '../../app/AuthProvider';
import api, { apiMessage } from '../../services/api';
import { ErrorPanel, Logo } from '../../components/ui';

function AuthFrame({ title, text, children }: { title: string; text: string; children: ReactNode }) {
  return <div className="auth-page"><section className="auth-cover"><Logo light/><div><h2 className="text-4xl font-bold">Seguridad ciudadana con información transparente.</h2><p className="mt-4 text-blue-100">AlertApp permite reportar y consultar incidentes con estados visibles y revisión operativa.</p></div><p className="text-sm text-blue-100">No reemplaza una denuncia formal o llamada de emergencia.</p></section><main className="auth-panel"><div className="auth-form"><Link to="/" className="mb-8 inline-flex md:hidden"><Logo/></Link><h1 className="text-3xl font-bold">{title}</h1><p className="mt-2 text-slate-500">{text}</p><div className="mt-8">{children}</div></div></main></div>;
}
const password = z.string().min(12, 'Mínimo 12 caracteres.').regex(/[A-Z]/, 'Incluye una mayúscula.').regex(/[a-z]/, 'Incluye una minúscula.').regex(/[0-9]/, 'Incluye un número.').regex(/[^A-Za-z0-9]/, 'Incluye un símbolo.');
const loginSchema = z.object({ email: z.string().email('Correo inválido.'), password: z.string().min(1, 'Ingresa tu contraseña.') });
export function LoginPage() {
  const [show, setShow] = useState(false); const [error, setError] = useState('');
  const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<z.infer<typeof loginSchema>>({ resolver: zodResolver(loginSchema) });
  const { login } = useAuth(); const navigate = useNavigate();
  const submit = handleSubmit(async (values) => { try { setError(''); const user = await login(values.email, values.password); navigate(user.role === 'ADMIN' ? '/admin' : user.role === 'AGENTE' ? '/agente' : '/ciudadano'); } catch (e) { setError(e instanceof Error ? e.message : 'No se pudo ingresar.'); } });
  return <AuthFrame title="Inicia sesión" text="Accede a tu espacio de AlertApp."><form onSubmit={submit} className="space-y-4">{error && <ErrorPanel message={error}/>}<label><span className="label">Correo electrónico</span><input className="input" type="email" autoComplete="email" {...register('email')}/>{errors.email && <small className="text-red-600">{errors.email.message}</small>}</label><label><span className="label">Contraseña</span><div className="relative"><input className="input pr-12" type={show ? 'text' : 'password'} autoComplete="current-password" {...register('password')}/><button type="button" aria-label={show ? 'Ocultar contraseña' : 'Mostrar contraseña'} onClick={() => setShow(!show)} className="absolute right-3 top-3 text-slate-500">{show ? <EyeOff size={20}/> : <Eye size={20}/>}</button></div>{errors.password && <small className="text-red-600">{errors.password.message}</small>}</label><div className="flex justify-end"><Link className="text-sm font-medium text-blue-600" to="/recuperar-password">¿Olvidaste tu contraseña?</Link></div><button className="btn-primary w-full" disabled={isSubmitting}>{isSubmitting ? 'Ingresando...' : 'Ingresar'}</button><p className="text-center text-sm text-slate-500">¿Aún no tienes cuenta? <Link className="font-semibold text-blue-600" to="/registro">Regístrate</Link></p></form></AuthFrame>;
}
const registerSchema = z.object({ nombres: z.string().trim().min(2, 'Ingresa tus nombres.'), apellidos: z.string().trim().min(2, 'Ingresa tus apellidos.'), email: z.string().email('Correo inválido.'), password, confirmPassword: z.string() }).refine((value) => value.password === value.confirmPassword, { path: ['confirmPassword'], message: 'Las contraseñas no coinciden.' });
export function RegisterPage() {
  const [success, setSuccess] = useState(''); const [error, setError] = useState(''); const [show, setShow] = useState(false);
  const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<z.infer<typeof registerSchema>>({ resolver: zodResolver(registerSchema) });
  const submit = handleSubmit(async (value) => { try { setError(''); await api.post('/auth/registro', { nombres: value.nombres, apellidos: value.apellidos, email: value.email, password: value.password }); setSuccess('Cuenta creada. Revisa tu correo para verificarla antes de iniciar sesión.'); } catch (e) { setError(apiMessage(e)); } });
  return <AuthFrame title="Crea tu cuenta" text="Regístrate como ciudadano para publicar reportes.">{success ? <div className="space-y-5 rounded-2xl bg-green-50 p-5 text-green-800"><ShieldCheck/><p>{success}</p><Link className="btn-primary" to="/login">Ir al login</Link></div> : <form onSubmit={submit} className="space-y-4">{error && <ErrorPanel message={error}/>}<div className="form-grid two"><label><span className="label">Nombres</span><input className="input" {...register('nombres')}/><small className="text-red-600">{errors.nombres?.message}</small></label><label><span className="label">Apellidos</span><input className="input" {...register('apellidos')}/><small className="text-red-600">{errors.apellidos?.message}</small></label></div><label><span className="label">Correo</span><input className="input" type="email" autoComplete="email" {...register('email')}/><small className="text-red-600">{errors.email?.message}</small></label><label><span className="label">Contraseña segura</span><div className="relative"><input className="input pr-12" type={show ? 'text' : 'password'} autoComplete="new-password" {...register('password')}/><button type="button" aria-label={show ? 'Ocultar contraseña' : 'Mostrar contraseña'} onClick={() => setShow(!show)} className="absolute right-3 top-3 text-slate-500">{show ? <EyeOff size={20}/> : <Eye size={20}/>}</button></div><small className="text-red-600">{errors.password?.message}</small></label><label><span className="label">Confirmar contraseña</span><input className="input" type={show ? 'text' : 'password'} autoComplete="new-password" {...register('confirmPassword')}/><small className="text-red-600">{errors.confirmPassword?.message}</small></label><button className="btn-primary w-full" disabled={isSubmitting}>{isSubmitting ? 'Registrando...' : 'Crear cuenta'}</button></form>}</AuthFrame>;
}
const forgotSchema = z.object({ email: z.string().email('Correo inválido.') });
export function ForgotPasswordPage() {
  const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<z.infer<typeof forgotSchema>>({ resolver: zodResolver(forgotSchema) });
  const submit = handleSubmit(async (value) => { try { setError(''); const { data } = await api.post('/auth/recuperar-password', value); setMessage(data.data.message); } catch (e) { setError(apiMessage(e)); } });
  return <AuthFrame title="Recupera tu acceso" text="Te enviaremos instrucciones al correo registrado."><form onSubmit={submit} className="space-y-4">{error && <ErrorPanel message={error}/>}<label><span className="label">Correo</span><input type="email" autoComplete="email" className="input" {...register('email')}/><small className="text-red-600">{errors.email?.message}</small></label><button disabled={isSubmitting} className="btn-primary w-full">{isSubmitting ? 'Enviando...' : 'Enviar instrucciones'}</button>{message && <p className="rounded-xl bg-blue-50 p-3 text-sm text-blue-700">{message}</p>}</form></AuthFrame>;
}
const resetSchema = z.object({ newPassword: password, confirmPassword: z.string() }).refine((value) => value.newPassword === value.confirmPassword, { path: ['confirmPassword'], message: 'Las contraseñas no coinciden.' });
export function ResetPasswordPage() {
  const [params] = useSearchParams(); const token = params.get('token') ?? ''; const [success, setSuccess] = useState(''); const [error, setError] = useState(''); const [show, setShow] = useState(false);
  const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<z.infer<typeof resetSchema>>({ resolver: zodResolver(resetSchema) });
  const submit = handleSubmit(async (value) => { if (!token) { setError('El enlace de recuperación no contiene un token válido.'); return; } try { setError(''); await api.post('/auth/restablecer-password', { token, newPassword: value.newPassword }); setSuccess('Contraseña actualizada. Ya puedes iniciar sesión.'); } catch (e) { setError(apiMessage(e)); } });
  return <AuthFrame title="Nueva contraseña" text="Establece una contraseña segura."><form onSubmit={submit} className="space-y-4">{error && <ErrorPanel message={error}/>}<label><span className="label">Nueva contraseña</span><div className="relative"><input className="input pr-12" type={show ? 'text' : 'password'} autoComplete="new-password" {...register('newPassword')}/><button type="button" aria-label={show ? 'Ocultar contraseña' : 'Mostrar contraseña'} onClick={() => setShow(!show)} className="absolute right-3 top-3 text-slate-500">{show ? <EyeOff size={20}/> : <Eye size={20}/>}</button></div><small className="text-red-600">{errors.newPassword?.message}</small></label><label><span className="label">Confirmar contraseña</span><input className="input" type={show ? 'text' : 'password'} autoComplete="new-password" {...register('confirmPassword')}/><small className="text-red-600">{errors.confirmPassword?.message}</small></label><button disabled={isSubmitting || !!success} className="btn-primary w-full">{isSubmitting ? 'Guardando...' : 'Guardar contraseña'}</button>{success && <p className="rounded-xl bg-green-50 p-3 text-sm text-green-700">{success}</p>}</form></AuthFrame>;
}
export function VerifyEmailPage() {
  const [params] = useSearchParams(); const token = params.get('token') ?? ''; const [msg, setMsg] = useState(token ? 'Verificando tu correo...' : 'El enlace de verificación no contiene un token válido.');
  useEffect(() => { if (!token) return; void api.post('/auth/verificar-email', { token }).then(() => setMsg('Correo verificado. Ya puedes iniciar sesión.')).catch((e) => setMsg(apiMessage(e))); }, [token]);
  return <AuthFrame title="Verificación" text="Confirmación de correo electrónico."><p className="rounded-xl bg-blue-50 p-4 text-blue-700">{msg}</p><Link className="btn-primary mt-5" to="/login">Ir al login</Link></AuthFrame>;
}
